# Setup
title:        GFMath
tagline:      Girls' Frontline, by the numbers.
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       BigStupidJellyfish

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
