# Setup
title:        GFMath
tagline:      Girls' Frontline, by the numbers.
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       BigStupidJellyfish
  url:        https://www.youtube.com/channel/UCXYXbrsfJJfvE5LJ9Bnu_fQ

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
